pr: none
trigger: none
schedules:
  - cron: '10 1,9,17 * * *'
    branches:
      include:
      - refs/tags/1.0.3a
    always: true
    displayName: Starting job
jobs:
  - job: swiftshader
    timeoutInMinutes: 180
    pool:
      vmImage: windows-latest
    strategy:
      maxParallel: 2
      matrix:
        LLVM:
          REACTOR_BACKEND: LLVM
        subzero:
          REACTOR_BACKEND: subzero
    steps:
      - checkout: none
      - script: |
          git clone --depth=1 https://github.com/google/swiftshader.git swiftshader
          git clone https://github.com/pal1000/swiftshader-dist-win.git swiftshader-dist-win
          cd swiftshader-dist-win
          git checkout 1.0.3a
          cd ..
        displayName: Get sources
      - script: swiftshader-dist-win\buildscript\ci\ci.cmd collectuids
        displayName: Collect code sources unique identifiers
      - task: Cache@2
        inputs:
          key: $(srcswiftshader) | $(distswiftshader)
          path: swiftshader-dist-win\buildscript\ci\assets-old
        displayName: Set a flag if build is up-to-date
      - script: swiftshader-dist-win\buildscript\ci\ci.cmd $(REACTOR_BACKEND)
        displayName: Build swiftshader
      - publish: swiftshader-dist-win\swiftshader-$(artifactuid)-$(REACTOR_BACKEND).7z
        artifact: swiftshader-$(artifactuid)-$(REACTOR_BACKEND).7z
      - publish: swiftshader-dist-win\dist\buildinfo\sources-unique-identifiers.html
        artifact: code-sources-unique-identifiers.html