name: swiftshader

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 8 * * *'
    - cron: '0 16 * * *'

jobs:
  swiftshader:
    runs-on: windows-latest
    timeout-minutes: 360
    strategy:
      max-parallel: 2
      matrix:
        backend: [LLVM10, subzero]

    steps:
      - name: Get sources
        run: |
          git clone --depth=1 https://swiftshader.googlesource.com/SwiftShader swiftshader
          git clone https://github.com/pal1000/swiftshader-dist-win.git swiftshader-dist-win
          cd swiftshader-dist-win
          git checkout 1.0.7.4

      - name: Collect code sources unique identifiers
        id: collectuids
        run: |
          echo "::set-output name=artifactuid::$(swiftshader-dist-win\\buildscript\\ci\\ci.cmd collectuids)"

      - name: Cache build assets
        id: cache
        uses: actions/cache@v3
        with:
          path: swiftshader-dist-win\buildscript\ci\assets
          key: ${{ matrix.backend }}-${{ steps.collectuids.outputs.artifactuid }}

      - name: Build SwiftShader
        run: swiftshader-dist-win\buildscript\ci\ci.cmd ${{ matrix.backend }}

      - name: Publish binaries package
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v3
        with:
          name: swiftshader-${{ steps.collectuids.outputs.artifactuid }}-${{ matrix.backend }}.7z
          path: swiftshader-dist-win\swiftshader-${{ steps.collectuids.outputs.artifactuid }}-${{ matrix.backend }}.7z

      - name: Publish build identification document
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v3
        with:
          name: code-sources-unique-identifiers.html
          path: swiftshader-dist-win\dist\buildinfo\sources-unique-identifiers.html
